# Generated by Django 3.2.10 on 2022-01-04 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=4096)),
                ('job', models.CharField(max_length=4096)),
                ('location', models.CharField(max_length=4096)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('csv_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('result_status', models.CharField(choices=[('PEN', 'Pending'), ('RUN', 'Running'), ('FIN', 'Finished')], default='PEN', max_length=3)),
            ],
            options={
                'db_table': 'scrappers_details',
                'managed': True,
            },
        ),
    ]
